// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3B9HzUFEKjpsVVcRECUUcKefOBdgaJw',
    appId: '1:778054954270:web:137e9c86f810c5fdb56d0f',
    messagingSenderId: '778054954270',
    projectId: 'dalili-app-f4792',
    authDomain: 'dalili-app-f4792.firebaseapp.com',
    storageBucket: 'dalili-app-f4792.firebasestorage.app',
    measurementId: 'G-N8J3QDK64W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz99ddSUKNpJMmnSS_QCPWurEdhrXLppI',
    appId: '1:778054954270:android:54d5a83f67df45ddb56d0f',
    messagingSenderId: '778054954270',
    projectId: 'dalili-app-f4792',
    storageBucket: 'dalili-app-f4792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6-_LwMZVs21F_dUmZiXgeCJPYjLG_IE',
    appId: '1:778054954270:ios:f61810160df51027b56d0f',
    messagingSenderId: '778054954270',
    projectId: 'dalili-app-f4792',
    storageBucket: 'dalili-app-f4792.firebasestorage.app',
    iosBundleId: 'com.example.daliliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6-_LwMZVs21F_dUmZiXgeCJPYjLG_IE',
    appId: '1:778054954270:ios:f61810160df51027b56d0f',
    messagingSenderId: '778054954270',
    projectId: 'dalili-app-f4792',
    storageBucket: 'dalili-app-f4792.firebasestorage.app',
    iosBundleId: 'com.example.daliliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk3B9HzUFEKjpsVVcRECUUcKefOBdgaJw',
    appId: '1:778054954270:web:6b238f2612ee61ddb56d0f',
    messagingSenderId: '778054954270',
    projectId: 'dalili-app-f4792',
    authDomain: 'dalili-app-f4792.firebaseapp.com',
    storageBucket: 'dalili-app-f4792.firebasestorage.app',
    measurementId: 'G-RJZF7R2FP1',
  );
}
